directories:
  output: package
  buildResources: build
appId: vitaeApp
productName: vitaeApp
copyright: Copyright © 2022 lyl
files:
  - filter:
      - dist/**/*
      - package.json
      - node_modules/
electronVersion: 11.1.1
